######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 30 14:01:58 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Cell.hpp Parameters.hpp RanGen.hpp Reactions.hpp Simulation.hpp
SOURCES += Cell.cpp main.cpp Reactions.cpp Simulation.cpp \
    Parameters.cpp
