# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0002_auto_20161116_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='name',
            field=models.TextField(default='default_name'),
        ),
    ]
