# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='name',
        ),
    ]
