# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulation', '0004_remove_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
