# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0008_auto_20170102_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='settings',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
